import { TextEdit, ScrollView, ComboBox, LineEdit, Palette, Button } from "std-widgets.slint";
import { EditorSpaceSettings } from "styling.slint";

export enum GradientKind {
    linear,
    radial
}
export struct GradientColor {
    value: color,
    location: percent}
export struct GradientData {
    gradient-kind: GradientKind,
    gradient-angle: length,
    gradient-colors: [GradientColor]
}
export component GradientDot inherits Rectangle {
    in property <percent> position;
    in property <color> value;
    in-out property <bool> selected: false;
    function enable() {
        root.selected = true;
    }
    function disable() {
        root.selected = false;
    }
    callback new-selection();
    width: self.selected ? 20px : 10px;
    height: self.selected ? 20px : 10px;
    border-radius: self.width;
    background: value;
    border-width: 1px;
    border-color: gray;
    TouchArea {
        clicked => {
            if !root.selected {
                ;
                new-selection();
            }
        }
    }
}

component EditGradientWidget inherits VerticalLayout {
    in property <bool> enabled;
    in property <string> property-name;
    in property <GradientData> property-value;
    height: self.preferred-height;
    padding: EditorSpaceSettings.default-padding;
    spacing: 8px;

    grad := Rectangle {
        height: 40px;
        background: @linear-gradient(90deg, #fff 0%, #f00 15%, #0af 60%, #000 100%);
        Rectangle {
            height: 1px;
            background: grey;
            for i[index] in [{ pos:0, value:#fff }, { pos:15, value:#f00 },{ pos:60, value:#0af },{ pos:100, value:#000 }]: GradientDot {
                selected: false;
                new-selection => {
                    self.selected = true;
                }
                x: i.pos * (grad.width - self.width) / 100;
                value: i.value;
            }
        }
    }

    VerticalLayout {
        alignment: stretch;
        spacing: 8px;
        vertical-stretch: 0;
        content := HorizontalLayout {
            alignment: start;
            spacing: EditorSpaceSettings.default-spacing;
            Text {
                vertical-alignment: center;
                text: "Type:";
            }

            cb-type:=ComboBox {
                horizontal-stretch: 0;
                width: 9rem;
                model: ["linear", "radial"];
            }
        }

        HorizontalLayout {
            visible: cb-type.current-value == "linear";
            height: content.preferred-height;
            alignment: start;
            spacing: EditorSpaceSettings.default-spacing;
            Text {
                vertical-alignment: center;
                text: "Angle:";
            }
            LineEdit {
                text: "-30";
                horizontal-alignment: right;
                width: 5rem;
            }

            ComboBox {
                width: 8rem;
                model: [
                    "Deg",
                    "rad",
                ];
            }

            VerticalLayout {
                Image {
                    source: @image-url("../assets/dial.svg");
                    colorize: Palette.alternate-foreground.transparentize(0.6);
                }
            }
        }
    }

    HorizontalLayout {
        height: content.preferred-height;
        alignment: space-between;
        spacing: 4px;
        HorizontalLayout {
            spacing: 4px;
            LineEdit {
                width: 9rem;
                text: "#ffffffff";
            }

            Rectangle {
                background: #fff;
                width: 40px;
            }
        }

        HorizontalLayout {
            spacing: 4px;
            Text {
                vertical-alignment: center;
                text: "Position:";
            }

            LineEdit {
                text: "0";
                width: 5rem;
            }
        }
    }
    Rectangle {height: EditorSpaceSettings.default-spacing;}
    HorizontalLayout {
        height: content.preferred-height;
        spacing: EditorSpaceSettings.default-spacing;
        Button {
            text: "Reset";
        }

        Button {
            text: "Code";
        }
    }
}

export component Example inherits Window {
    width: 360px;
    EditGradientWidget { }
}
