import { Button, Palette, StandardButton, ScrollView } from "std-widgets.slint";
import { EditorSpaceSettings } from "../components/styling.slint";
import { Spreadsheet } from "../components/spreadsheet.slint";
import { Api, PreviewData, PropertyValueTable } from "../api.slint";

import { WindowGlobal } from "../windowglobal.slint";
import { EditorSizeSettings } from "styling.slint";

component SpreadsheetPopup inherits PopupWindow {
    in property <string> property-group-id;
    in property <PreviewData> preview-data;
    in property <PropertyValueTable> current-table;

    width: spread-sheet.preferred-width;
    height: spread-sheet.preferred-height;
    x: (WindowGlobal.window-width - self.width)/2;
    y: (WindowGlobal.window-height - self.height)/2;
    close-policy: close-on-click-outside;

    Rectangle {
        background: Palette.alternate-background;
        drop-shadow-blur: 30px;
        drop-shadow-color: black.transparentize(0.5);
        
        VerticalLayout {
            Dialog {
                title: root.preview-data.has-setter ? "Edit Values" : "View Values"; 
                VerticalLayout {
                    padding-top: EditorSpaceSettings.default-padding;
                    spacing: EditorSpaceSettings.default-spacing;
                    Text {
                        text: spread-sheet.preview-data.name;
                        horizontal-alignment: center;
                        font-weight: 800;
                    }
                    HorizontalLayout {
                        ScrollView {
                        width: spread-sheet.preferred-width;
                        height: spread-sheet.preferred-height; 
                        spread-sheet := Spreadsheet {              
                            property-group-id <=> root.property-group-id;
                            preview-data <=> root.preview-data;
                            current-table <=> root.current-table;
                        }
                        // Rectangle {width:200px;}
                    }
                    }
                    // Rectangle { height: 200px; }
                }

                StandardButton {
                    kind: StandardButtonKind.ok;
                    clicked => {
                        // TODO: Apply changes!
                        root.close();
                    }
                }
                StandardButton {
                    kind: StandardButtonKind.cancel;
                    clicked => { root.close(); }
                }
            }
        }
        }
}

export component SpreadsheetDialog {
    private property <string> property-group-id;
    private property <PreviewData> preview-data;
    private property <PropertyValueTable> current-table;

    public function edit-in-spreadsheet(property-group-id: string, data: PreviewData) {
        root.property-group-id = property-group-id;
        root.preview-data = data;
        root.current-table = Api.get-property-value-table(property-group-id, data.name);

        spreadsheet.show();
    }
    x:0;
    y:0;
    spreadsheet := SpreadsheetPopup {
        property-group-id <=> root.property-group-id;
        preview-data <=> root.preview-data;
        current-table <=> root.current-table;
    }
}
